/*
 * -----------------------------------------------------------
 *  Module  : scaffolder
 *  Project : nhmysql - MySQL Model Generator for Rust
 *  Author  : Nurul Huda, S.Kom
 *  Contact : +62823-1371-4009
 * -----------------------------------------------------------
 */

use anyhow::{anyhow, Result};
use console::style;
use dialoguer::{Input, Password};
use std::fs;
use std::path::Path;

/// Interactive setup: ask user for DB credentials, generate .env, update Cargo.toml and main.rs
pub fn setup_database_url() -> Result<String> {
    // 1. Collect database credentials interactively
    println!("{}", style("Step 1: Database Configuration").yellow().bold());
    println!();

    let host: String = Input::new()
        .with_prompt("Host")
        .default("127.0.0.1".into())
        .interact_text()
        .map_err(|_| anyhow!("Failed to read host"))?;

    let port: String = Input::new()
        .with_prompt("Port")
        .default("3306".into())
        .interact_text()
        .map_err(|_| anyhow!("Failed to read port"))?;

    let username: String = Input::new()
        .with_prompt("Username")
        .default("root".into())
        .interact_text()
        .map_err(|_| anyhow!("Failed to read username"))?;

    let password = Password::new()
        .with_prompt("Password")
        .interact()
        .map_err(|_| anyhow!("Failed to read password"))?;

    let database: String = Input::new()
        .with_prompt("Database name")
        .interact_text()
        .map_err(|_| anyhow!("Failed to read database name"))?;

    // URL-encode the password (handle special characters like #, @, %)
    let encoded_password = url_encode(&password);

    let database_url = format!(
        "mysql://{}:{}@{}:{}/{}",
        username, encoded_password, host, port, database
    );

    println!();

    // 2. Create .env file
    println!("{}", style("Step 2: Creating .env file").yellow().bold());
    create_env_file(&database_url)?;
    println!("  {}", style(".env file created").green());

    // 3. Update Cargo.toml (add dotenv-ng, console, dialoguer)
    println!();
    println!("{}", style("Step 3: Updating Cargo.toml").yellow().bold());
    update_cargo_toml()?;
    println!("  dotenv-ng added to Cargo.toml");

    // 4. Update main.rs (add dotenv loader)
    println!();
    println!("{}", style("Step 4: Updating main.rs").yellow().bold());
    update_main_rs()?;
    println!("  dotenv loader added to main.rs");

    // 5. Update .gitignore
    println!();
    println!("{}", style("Step 5: Updating .gitignore").yellow().bold());
    update_gitignore()?;
    println!("  .env added to .gitignore");

    println!();
    println!(
        "{}",
        style("Setup complete! DATABASE_URL is ready.")
            .green()
            .bold()
    );

    Ok(database_url)
}

/// Create .env file with DATABASE_URL
fn create_env_file(database_url: &str) -> Result<()> {
    let env_content = format!(
        "# Database Configuration\n# Generated by nhmysql - {}\n\nDATABASE_URL={}\n",
        chrono::Local::now().format("%Y-%m-%d %H:%M:%S"),
        database_url
    );

    if Path::new(".env").exists() {
        println!("  {}", style(".env already exists, skipping").yellow());
    } else {
        fs::write(".env", env_content)?;
    }

    Ok(())
}

/// Add dotenv-ng dependency to Cargo.toml if not present
fn update_cargo_toml() -> Result<()> {
    let cargo_path = Path::new("Cargo.toml");

    if !cargo_path.exists() {
        println!("  {}", style("Cargo.toml not found, skipping").yellow());
        return Ok(());
    }

    let content = fs::read_to_string(cargo_path)?;
    let mut modified = false;

    // Add dotenv-ng if not present
    if !content.contains("dotenv") && !content.contains("dotenv-ng") {
        if content.contains("[dependencies]") {
            // Add dotenv-ng after [dependencies]
            let updated = content.replace(
                "[dependencies]",
                "[dependencies]\ndotenv = { package = \"dotenv-ng\", version = \"1\" }",
            );
            fs::write(cargo_path, updated)?;
            modified = true;
        }
    }

    if !modified {
        println!(
            "  {}",
            style("dotenv-ng already present in Cargo.toml").yellow()
        );
    }

    Ok(())
}

/// Add dotenv loader to main.rs if not present
fn update_main_rs() -> Result<()> {
    let main_path = Path::new("src/main.rs");

    if !main_path.exists() {
        println!("  {} src/main.rs not found, skipping", style("Warning:").yellow());
        return Ok(());
    }

    let content = fs::read_to_string(main_path)?;

    // Check if dotenv is already imported
    let has_dotenv_use = content.contains("use dotenv") || content.contains("dotenv::");
    let has_dotenv_load = content.contains("dotenv::EnvLoader") || content.contains("dotenv::dotenv");

    if has_dotenv_use && has_dotenv_load {
        println!(
            "  {}",
            style("dotenv already configured in main.rs").yellow()
        );
        return Ok(());
    }

    let mut lines: Vec<String> = content.lines().map(|l| l.to_string()).collect();

    // 1. Add use statement after last `use` line (or after `mod` lines)
    if !has_dotenv_use {
        let last_use_idx = lines
            .iter()
            .rposition(|l| l.trim_start().starts_with("use ") || l.trim_start().starts_with("mod "));

        if let Some(idx) = last_use_idx {
            lines.insert(idx + 1, "use dotenv::EnvLoader;".to_string());
        } else {
            // No use statements found, add at top
            lines.insert(0, "use dotenv::EnvLoader;".to_string());
        }
    }

    // 2. Add dotenv loader as first line in main() function (after async fn main() {)
    if !has_dotenv_load {
        let main_fn_idx = lines.iter().position(|l| l.contains("fn main()"));

        if let Some(idx) = main_fn_idx {
            // Find the opening brace
            let brace_idx = lines[idx..]
                .iter()
                .position(|l| l.contains('{'))
                .map(|p| p + idx);

            if let Some(brace_idx) = brace_idx {
                // Check if next line after brace is empty or not dotenv
                let insert_at = brace_idx + 1;
                let loader_line = "    let _ = dotenv::EnvLoader::new().load();";

                // Only insert if not already there
                if !lines.iter().any(|l| l.contains("EnvLoader") || l.contains("dotenv::dotenv")) {
                    lines.insert(insert_at, String::new());
                    lines.insert(insert_at + 1, loader_line.to_string());
                }
            }
        }
    }

    let updated = lines.join("\n");
    fs::write(main_path, updated)?;

    Ok(())
}

/// Add .env to .gitignore if not present
fn update_gitignore() -> Result<()> {
    let gitignore_path = Path::new(".gitignore");

    if !gitignore_path.exists() {
        fs::write(gitignore_path, "# Environment variables\n.env\n")?;
        return Ok(());
    }

    let content = fs::read_to_string(gitignore_path)?;

    if !content.contains(".env") {
        let mut updated = content.trim_end().to_string();
        updated.push_str("\n\n# Environment variables\n.env\n");
        fs::write(gitignore_path, updated)?;
    } else {
        println!(
            "  {}",
            style(".env already in .gitignore").yellow()
        );
    }

    Ok(())
}

/// URL-encode special characters for use in DATABASE_URL
fn url_encode(input: &str) -> String {
    let mut encoded = String::new();
    for byte in input.bytes() {
        match byte {
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~' => {
                encoded.push(byte as char);
            }
            _ => {
                encoded.push('%');
                encoded.push_str(&format!("{:02X}", byte));
            }
        }
    }
    encoded
}
